library(shiny)
library(DT)
shinyUI(fluidPage(
  titlePanel("Blast against Mp transcriptome"),
  sidebarLayout(
    sidebarPanel(
      radioButtons("radio", label = h3("Blast options"),
             choices = list("tblastx" = 1, "tblastn" = 2), 
             selected = 1),
      textInput("text", label = h3("Sequence input"),width="100%")
  #submitButton("BLAST")
  #"TTCGATGATAATAAGTTTGTCAACGACCACTTTGTTCAATCACAACCACAATTAATCTTCCGAACCGAGTCTAAGATTTATTCGGTAGCCGTAAATTTCAAAGGTCCACGGATAGAGGTCCATGAGTTACCCTTAGCCATTCCTGGTTTGAAATCTGAGATGCCGATACGGCTACACGACTATGTTGATTGTGATGGCTTGTTGTTTTGTACTAGCTACTTTAACGGGGTCTTGATTTGGAACCCCTGGTTGAGACAAACTAGATTTTTCCCATCCATACATCGTTATCCAGTCACATATGACATAGGTTATGATAACAAAAAACAATACAAGATGCTCGATTATTATAAATGTGAAGGTGACTCATCAATAAAATCCATAATTTATGAGATTGGGTTATATTCAAAGAAAGTTAAAGATTTGGAGTCTGATAGTACTTGGTCAATTTTCCAATCAAATAGCGTATCTCTGAATGGAACTTTGTATTGGGCTGGTGTAGATGTTAACAATGGTATTTTCATTAGAAGCTTCAGTTTTTCAACAGAAAAACCAAGAACTTTTTGTAGTCTACCGTTTATGTACGATGACGACAATGTTCTAGCCCTTGCGGTTTTTAGGAAAGATCGTCTTTCATTGTTAAACTTATGCAATAAAACATCAGAGATAAAGATTTGGTTGACAAAGAATAATATCAATGATAGGGAGGTAGGATTAGAAGAGGACGTGGTGTGGATAAACCTCATGACAGTGTTAATACCTAATTTCCCTAAATTTTCATTTTATTGGTATAACCGTCCTGACCTAACTTACTTCCTCGACAACGATGATGCTAAGAGGCTTGTCATTTGTTGTTATGATGAAACTGATCAGGCTTACATCTACATTGTAAAAGGAGATATGTTCAAGAAAATCAAAATAGATCAGTATGAGGTTCTATCTGATTATTCTCGCCCGCACTTCCATACTTATATCCCCAGTTTGGTTCGGCCTTCCCGGGTCAAAGAGGACAACAAGAATTAA"),
  #numericInput("num", label = h3("Numeric input"), value = 0,width="100%")
  #submitButton("Submit")
  ),
 #fluidRow(
  mainPanel(
    tabsetPanel(
      tabPanel('Hits',DT::dataTableOutput("Results")),
      tabPanel('Sequence',verbatimTextOutput("seq"))))#,DT::dataTableOutput('x1')),
)))

