#"TTCGATGATAATAAGTTTGTCAACGACCACTTTGTTCAATCACAACCACAATTAATCTTCCGAACCGAGTCTAAGATTTATTCGGTAGCCGTAAATTTCAAAGGTCCACGGATAGAGGTCCATGAGTTACCCTTAGCCATTCCTGGTTTGAAATCTGAGATGCCGATACGGCTACACGACTATGTTGATTGTGATGGCTTGTTGTTTTGTACTAGCTACTTTAACGGGGTCTTGATTTGGAACCCCTGGTTGAGACAAACTAGATTTTTCCCATCCATACATCGTTATCCAGTCACATATGACATAGGTTATGATAACAAAAAACAATACAAGATGCTCGATTATTATAAATGTGAAGGTGACTCATCAATAAAATCCATAATTTATGAGATTGGGTTATATTCAAAGAAAGTTAAAGATTTGGAGTCTGATAGTACTTGGTCAATTTTCCAATCAAATAGCGTATCTCTGAATGGAACTTTGTATTGGGCTGGTGTAGATGTTAACAATGGTATTTTCATTAGAAGCTTCAGTTTTTCAACAGAAAAACCAAGAACTTTTTGTAGTCTACCGTTTATGTACGATGACGACAATGTTCTAGCCCTTGCGGTTTTTAGGAAAGATCGTCTTTCATTGTTAAACTTATGCAATAAAACATCAGAGATAAAGATTTGGTTGACAAAGAATAATATCAATGATAGGGAGGTAGGATTAGAAGAGGACGTGGTGTGGATAAACCTCATGACAGTGTTAATACCTAATTTCCCTAAATTTTCATTTTATTGGTATAACCGTCCTGACCTAACTTACTTCCTCGACAACGATGATGCTAAGAGGCTTGTCATTTGTTGTTATGATGAAACTGATCAGGCTTACATCTACATTGTAAAAGGAGATATGTTCAAGAAAATCAAAATAGATCAGTATGAGGTTCTATCTGATTATTCTCGCCCGCACTTCCATACTTATATCCCCAGTTTGGTTCGGCCTTCCCGGGTCAAAGAGGACAACAAGAATTAA"),


library(shiny)
library(DT)
shinyUI(fluidPage(
  titlePanel("Blast against Mp transcriptome"),
  sidebarLayout(
    sidebarPanel(
      img(src='250px-Moos_5772.jpg', align = "left", width='50%'),
      img(src='download.jpeg', align = "right", width='50%'),
      div(),
      #hr(),
      tags$p(),
      radioButtons("radio",label="",
             choices = list("tblastx" = 1, "tblastn" = 2), 
             selected = 1),
      textInput("text", label = ("Sequence input"),width="100%"),
      #tags$hr(),
  
  numericInput("num", label = ("Extra bp up- and down-stream"), value = 0,width="100%"),
  radioButtons("type",label = ("Gene or transcript"),
               choices = list("transcript sequence"=1, "genomic sequence" = 2),
               selected = 2)
  ),
  mainPanel(
   
    tabsetPanel(
      tabPanel('Hits',DT::dataTableOutput("Results")),
      tabPanel('Sequence',hr(),downloadButton('downloadFasta', 'Download as fasta file'),hr(),htmlOutput("seq")))
))))

